db_conf:
  id: 125
  flavor: "mariadb"
  user: "root"
  pwd: "Since18!"
  host: "127.0.0.1:3310"
  port: 3306
  architecture: "default"
#  binlog_pos:
#    binlog: "binlog.000001"
#    offset: 4

redis_conf:
  host: "localhost"
  port: 6379


kafka_conf:
  address: "127.0.0.1:9092"
  channel_config:
    topic: "go-mysql-kafka-binlog"
    field_name: "id"
    partition_num: 3
    strategy: "partition_by_key"

metric_conf:
  addr: "localhost:8080"
  path: "/delay"


